version: '3.9'

services:
  app:
    container_name: tests
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "uvicorn app:app --reload --host 0.0.0.0 --port 8000"
    volumes:
      - ./src:/app/src
    depends_on:
      - db
    ports:
      - "${WEB_EXTERNAL_PORT:-8000}:8000"
    restart: unless-stopped
    tty: true

  db:
    container_name: tests-db
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "${DB_EXTERNAL_PORT:-5432}:5432"
    expose:
      - 5432
    environment:
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-password}
      POSTGRES_DB: ${DATABASE_NAME:-test}
    restart: unless-stopped
    tty: true

volumes:
  postgres_data: { }
